(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const track=(event,payload={})=>{try{if(window.CTI_RC11&&window.CTI_RC11.track)window.CTI_RC11.track(event,payload);else if(Array.isArray(window.dataLayer))window.dataLayer.push({event,...payload});}catch(_){}};
const seen=new Set();
function packageName(el){return (el.dataset.package||'').toLowerCase()||null}
function openQualification(pkg,source,label){const form=$('#pricing-qualification');if(!form)return;const interest=$('[name="package_interest"]',form);if(interest&&pkg)interest.value=pkg;form.dataset.sourceSection=source||'pricing';track('cta_click',{package_name:pkg||'',cta_label:label||'',section:source||'',page_path:location.pathname});form.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});setTimeout(()=>{const first=$('input,select,textarea',form);if(first)first.focus({preventScroll:true})},350)}
function bindCtas(){$$('[data-pricing-cta]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openQualification(packageName(a),a.dataset.section||'pricing',a.textContent.trim())}))}
function observePackages(){const cards=$$('[data-package-card]');if(!('IntersectionObserver'in window)){cards.forEach(c=>emitPackage(c));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>=.45)emitPackage(e.target)}),{threshold:[.45]});cards.forEach(c=>io.observe(c))}
function emitPackage(c){const key=c.dataset.package;if(!key||seen.has(key))return;seen.add(key);track('package_view',{package_name:key,displayed_price:c.dataset.price||'',viewport:innerWidth<768?'mobile':innerWidth<1100?'tablet':'desktop'})}
function bindFaq(){$$('.faq-item button').forEach(btn=>btn.addEventListener('click',()=>{const item=btn.closest('.faq-item'),open=btn.getAttribute('aria-expanded')==='true';$$('.faq-item button').forEach(b=>{b.setAttribute('aria-expanded','false');const p=$('#'+b.getAttribute('aria-controls'));if(p)p.hidden=true});if(!open){btn.setAttribute('aria-expanded','true');const p=$('#'+btn.getAttribute('aria-controls'));if(p)p.hidden=false}}))}
function field(f,n){const e=f.elements.namedItem(n);return e?String(e.value||'').trim():''}
function bindForm(){const f=$('#pricing-qualification');if(!f)return;let started=false;const markStart=()=>{if(started)return;started=true;track('pricing_form_start',{package_interest:field(f,'package_interest'),source_section:f.dataset.sourceSection||'pricing'})};f.addEventListener('input',markStart,{once:false});f.addEventListener('change',markStart,{once:false});f.addEventListener('submit',async e=>{e.preventDefault();if(!f.reportValidity())return;const submit=$('[type="submit"]',f),status=$('[data-form-status]',f);if(submit)submit.disabled=true;if(status){status.textContent='Submitting…';status.focus?.()}const payload={schema:'cti.website_lead.v2',identity:{name:(field(f,'first_name')+' '+field(f,'last_name')).trim(),email:field(f,'business_email'),company:field(f,'company'),role:field(f,'job_title')},permission:{privacyAccepted:true,marketingConsent:!!f.elements.namedItem('marketing_consent')?.checked,consentVersion:'pricing-2026-08-13',consentTs:new Date().toISOString()},intent:{type:'pricing_program_interest',topic:field(f,'package_interest'),message:'Pricing qualification request',programObjective:field(f,'program_objective'),targetMarket:field(f,'target_market'),programTiming:field(f,'program_timing'),packageInterest:field(f,'package_interest'),scopeType:field(f,'scope_type'),buyingProcess:field(f,'buying_process'),budgetStatus:field(f,'budget_status'),companyWebsite:field(f,'company_website'),countryRegion:field(f,'country_region')},attribution:(window.CTI_RC11&&window.CTI_RC11.attribution)?window.CTI_RC11.attribution():{}};track('pricing_form_submit',{package_interest:payload.intent.packageInterest,program_objective:payload.intent.programObjective,program_timing:payload.intent.programTiming,scope_type:payload.intent.scopeType});try{const id='pricing:'+crypto.randomUUID();const r=await fetch('/api/website-leads.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Idempotency-Key':id,'X-CTI-Source':'pricing'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||('HTTP '+r.status));sessionStorage.setItem('cti:last_lead_request',d.requestId||id);location.assign(d.redirect||'/thank-you.html')}catch(err){if(status)status.textContent='Submission could not be completed. Please review your details and retry.';if(submit)submit.disabled=false;track('pricing_form_error',{error:String(err.message||err)})}})}
function boot(){track('pricing_page_view',{page_path:location.pathname});bindCtas();observePackages();bindFaq();bindForm()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();