(function(){
'use strict';
var route=(location.hash||'').replace(/^#\/?/,'').split('?')[0];
var typeMap={blog:'blog',research:'research','case-studies':'case-study'};
function track(n,d){if(window.CTI_RC11&&window.CTI_RC11.track)window.CTI_RC11.track(n,d||{});}
function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;}
function findEmpty(){return Array.from(document.querySelectorAll('main,section,div')).find(function(n){return /Content API is unavailable\.|Vendor API unavailable\./.test(n.textContent||'');});}
function card(item){var a=el('article','cti-cms-card');var meta=el('div','cti-cms-meta',(item.category||item.type||'Intelligence').toUpperCase()+(item.publishedAt?' · '+new Date(item.publishedAt).toLocaleDateString():''));var h=el('h2','cti-cms-title',item.title);var p=el('p','cti-cms-dek',item.dek||'');a.append(meta,h,p);if(item.metrics&&Object.keys(item.metrics).length){var m=el('div','cti-metrics');Object.keys(item.metrics).slice(0,4).forEach(function(k){var x=el('div','cti-metric');x.append(el('strong','',String(item.metrics[k])),el('span','',k));m.append(x)});a.append(m)}return a;}
function renderContent(data){var root=findEmpty();if(!root)return;root.innerHTML='';root.classList.add('cti-cms-root');var bar=el('div','cti-cms-toolbar');bar.append(el('span','cti-live-dot','LIVE'),el('span','',data.count+' published'));root.append(bar);var grid=el('div','cti-cms-grid');data.items.forEach(function(i){grid.append(card(i))});if(!data.items.length)grid.append(el('div','cti-cms-empty','No published items yet.'));root.append(grid);if(route==='case-studies'&&data.items.length>1)renderCompare(root,data.items);track('cms_content_loaded',{route:route,count:data.count});}
function renderCompare(root,items){var section=el('section','cti-compare');section.append(el('div','cti-eyebrow','DECISION EVIDENCE'),el('h2','cti-compare-heading','Compare outcomes, evidence and activation patterns.'));var controls=el('div','cti-compare-controls');var selected=items.slice(0,3);selected.forEach(function(i){controls.append(el('button','cti-chip',i.title))});section.append(controls);var table=el('div','cti-compare-table');var dimensions=['Challenge','Approach','Outcome','Evidence'];dimensions.forEach(function(dim){var row=el('div','cti-compare-row');row.append(el('strong','cti-compare-label',dim));selected.forEach(function(i){var value=(i.comparison&&i.comparison[dim.toLowerCase()])||(dim==='Outcome'&&i.dek)||(dim==='Evidence'&&(i.evidenceIds||[]).join(', '))||'—';row.append(el('div','',String(value)))});table.append(row)});section.append(table);root.append(section);}
function renderVendors(data){var root=findEmpty();if(!root)return;root.innerHTML='';root.classList.add('cti-cms-root');var stats=Array.from(document.querySelectorAll('body *')).filter(function(n){return ['Tracked vendors','Categories','Priority records'].includes((n.textContent||'').trim())});stats.forEach(function(label){var p=label.parentElement;if(!p)return;var val=p.querySelector('div,span,strong');var text=label.textContent.trim();var num=text==='Tracked vendors'?data.stats.tracked:text==='Categories'?data.stats.categories:data.stats.priority;Array.from(p.children).forEach(function(c){if(/^\s*0\s*$/.test(c.textContent||''))c.textContent=String(num)})});var grid=el('div','cti-cms-grid');data.vendors.forEach(function(v){var c=el('article','cti-cms-card');c.append(el('div','cti-cms-meta',(v.category||'Vendor')+(v.priority?' · PRIORITY':'')),el('h2','cti-cms-title',v.name),el('p','cti-cms-dek',v.summary||''));grid.append(c)});if(!data.vendors.length)grid.append(el('div','cti-cms-empty','Vendor catalog is connected. No published vendors yet.'));root.append(grid);track('vendor_api_loaded',{count:data.stats.tracked});}
function load(){var url=route==='vendors'?'/api/vendors':'/api/content?type='+encodeURIComponent(typeMap[route]||'');if(route!=='vendors'&&!typeMap[route])return;fetch(url,{credentials:'same-origin',cache:'no-store'}).then(function(r){if(!r.ok)throw Error('http_'+r.status);return r.json()}).then(function(d){route==='vendors'?renderVendors(d):renderContent(d)}).catch(function(e){track('dynamic_cms_unavailable',{route:route,error:String(e.message||e)})});}
var css='.cti-cms-root{max-width:1200px;margin:0 auto;padding:48px 28px 80px}.cti-cms-toolbar{display:flex;gap:12px;align-items:center;margin-bottom:24px;color:#9aa3b2}.cti-live-dot{color:#21e6e6;font:600 11px monospace;letter-spacing:.14em}.cti-cms-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}.cti-cms-card{border:1px solid #252b34;background:#101216;border-radius:14px;padding:28px;transition:transform .28s ease,border-color .28s ease,background .28s ease}.cti-cms-card:hover{transform:translateY(-4px);border-color:#3b4654;background:#12161b}.cti-cms-meta,.cti-eyebrow{font:600 11px monospace;letter-spacing:.14em;color:#21e6e6}.cti-cms-title{font-size:24px;line-height:1.15;margin:14px 0 10px}.cti-cms-dek{color:#9aa3b2;line-height:1.6}.cti-metrics{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:22px}.cti-metric{border-top:1px solid #252b34;padding-top:10px}.cti-metric strong,.cti-metric span{display:block}.cti-metric span{font-size:12px;color:#8e97a5}.cti-compare{margin-top:64px;padding-top:48px;border-top:1px solid #252b34}.cti-compare-heading{font-size:clamp(28px,4vw,48px);max-width:760px}.cti-compare-controls{display:flex;gap:8px;flex-wrap:wrap;margin:24px 0}.cti-chip{border:1px solid #303844;background:#15191f;color:#eef2f6;border-radius:999px;padding:9px 14px}.cti-compare-table{overflow:auto;border:1px solid #252b34;border-radius:14px}.cti-compare-row{display:grid;grid-template-columns:150px repeat(3,minmax(220px,1fr));border-bottom:1px solid #252b34}.cti-compare-row:last-child{border-bottom:0}.cti-compare-row>*{padding:18px;border-right:1px solid #252b34}.cti-compare-row>*:last-child{border-right:0}.cti-compare-label{color:#21e6e6}@media(max-width:720px){.cti-cms-root{padding:32px 20px}.cti-compare-row{grid-template-columns:120px repeat(3,240px)}}@media(prefers-reduced-motion:reduce){.cti-cms-card{transition:none}.cti-cms-card:hover{transform:none}}';var s=document.createElement('style');s.textContent=css;document.head.appendChild(s);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();window.addEventListener('hashchange',function(){route=(location.hash||'').replace(/^#\/?/,'').split('?')[0];load()});
})();
