(function(){
'use strict';
function currentRoute(){var h=(location.hash||'').replace(/^#\/?/,'').split('?')[0];if(h)return h;var p=(location.pathname.split('/').pop()||'index.html').replace(/\.html$/,'');return p==='index'?'':p;}
var route=currentRoute();
var typeMap={blog:'blog',research:'research','case-studies':'case-study',resources:'resource'};
function track(n,d){if(window.CTI_RC11&&window.CTI_RC11.track)window.CTI_RC11.track(n,d||{});}
function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;}
function findEmpty(){return Array.from(document.querySelectorAll('main,section,div')).find(function(n){return /Content API is unavailable\.|Vendor API unavailable\.|No published items yet\.|Publishing system connected/.test(n.textContent||'');});}
function routeParts(){return route.split('/').filter(Boolean)}
function contentHref(item){var parts=routeParts();var base=parts[0]||route||item.type;return '#/'+base+'/'+item.slug;}
function card(item){var a=el('article','cti-cms-card');var link=el('a','cti-cms-link');link.href=contentHref(item);link.append(el('div','cti-cms-meta',(item.category||item.type||'Intelligence').toUpperCase()+(item.publishedAt?' · '+new Date(item.publishedAt).toLocaleDateString():'')),el('h2','cti-cms-title',item.title),el('p','cti-cms-dek',item.dek||''),el('span','cti-cms-read','Read →'));a.append(link);return a;}
function detail(item){var root=findEmpty()||document.querySelector('main');if(!root)return;root.innerHTML='';root.classList.add('cti-cms-root','cti-cms-detail');var back=el('a','cti-cms-back','← Back');var base=routeParts()[0]||item.type;back.href='#/'+base;root.append(back,el('div','cti-cms-meta',(item.category||item.type||'Intelligence').toUpperCase()+(item.publishedAt?' · '+new Date(item.publishedAt).toLocaleDateString():'')),el('h1','cti-cms-detail-title',item.title),el('p','cti-cms-detail-dek',item.dek||''));if(item.heroImage){var img=document.createElement('img');img.className='cti-cms-hero';img.src=item.heroImage;img.alt='';root.append(img)}var body=el('div','cti-cms-body');String(item.body||'').split(/\n{2,}/).filter(Boolean).forEach(function(p){body.append(el('p','',p))});root.append(body);track('cms_detail_loaded',{type:item.type,slug:item.slug});}
function renderContent(data){var parts=routeParts();if(parts[1]){if(data.items&&data.items[0])detail(data.items[0]);return}var root=findEmpty();if(!root)return;root.innerHTML='';root.classList.add('cti-cms-root');var bar=el('div','cti-cms-toolbar');bar.append(el('span','cti-live-dot','PUBLISHED'),el('span','',data.count+' items'));root.append(bar);var grid=el('div','cti-cms-grid');(data.items||[]).forEach(function(i){grid.append(card(i))});if(!data.items||!data.items.length)grid.append(el('div','cti-cms-empty','Publishing system connected. No published items in this channel yet.'));root.append(grid);track('cms_content_loaded',{route:route,count:data.count||0});}
function vendorHref(v){return '#/vendors/'+v.slug}
function vendorDetail(v){var root=findEmpty()||document.querySelector('main');if(!root)return;root.innerHTML='';root.classList.add('cti-cms-root','cti-cms-detail');var back=el('a','cti-cms-back','← Back to Vendor Intelligence');back.href='#/vendors';root.append(back,el('div','cti-cms-meta',(v.category||'Vendor').toUpperCase()+(v.priority?' · PRIORITY':'')),el('h1','cti-cms-detail-title',v.name),el('p','cti-cms-detail-dek',v.summary||''));if(v.buyingTriggers&&v.buyingTriggers.length){var ul=el('ul','cti-cms-body');v.buyingTriggers.forEach(function(x){ul.append(el('li','',x))});root.append(ul)}track('vendor_detail_loaded',{slug:v.slug});}
function renderVendors(data){var parts=routeParts();if(parts[1]){if(data.vendors&&data.vendors[0])vendorDetail(data.vendors[0]);return}var root=findEmpty();if(!root)return;root.innerHTML='';root.classList.add('cti-cms-root');var grid=el('div','cti-cms-grid');(data.vendors||[]).forEach(function(v){var c=el('article','cti-cms-card');var a=el('a','cti-cms-link');a.href=vendorHref(v);a.append(el('div','cti-cms-meta',(v.category||'Vendor')+(v.priority?' · PRIORITY':'')),el('h2','cti-cms-title',v.name),el('p','cti-cms-dek',v.summary||''),el('span','cti-cms-read','View intelligence →'));c.append(a);grid.append(c)});if(!data.vendors||!data.vendors.length)grid.append(el('div','cti-cms-empty','Vendor intelligence publishing is connected. Catalog records will appear after approval.'));root.append(grid);track('vendor_api_loaded',{count:(data.stats&&data.stats.tracked)||(data.vendors||[]).length});}
function load(){route=currentRoute();var cfg=window.CTI_CONVERSION||{};var parts=routeParts();var base=parts[0]||route;var slug=parts[1]||'';var isVendor=base==='vendors';var type=typeMap[base];if(!isVendor&&!type)return;var url=isVendor?(cfg.vendorsPath||'/api/vendors.php'):(cfg.contentPath||'/api/content.php')+'?type='+encodeURIComponent(type);if(slug)url+=(isVendor?'?':'&')+'slug='+encodeURIComponent(slug);fetch(url,{credentials:'same-origin',cache:'no-store'}).then(function(r){if(!r.ok)throw Error('http_'+r.status);return r.json()}).then(function(d){isVendor?renderVendors(d):renderContent(d)}).catch(function(e){var root=findEmpty();if(root){root.innerHTML='';root.classList.add('cti-cms-root');root.append(el('div','cti-cms-empty','Publishing service is temporarily unavailable. Core site navigation and buyer workflows remain available.'));}track('dynamic_cms_unavailable',{route:route,error:String(e.message||e)});});}
var css='.cti-cms-root{max-width:1200px;margin:0 auto;padding:48px 28px 80px}.cti-cms-toolbar{display:flex;gap:12px;align-items:center;margin-bottom:24px;color:#9aa3b2}.cti-live-dot{color:#21e6e6;font:600 11px monospace;letter-spacing:.14em}.cti-cms-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}.cti-cms-card,.cti-cms-empty{border:1px solid #252b34;background:#101216;border-radius:14px;padding:28px}.cti-cms-link{display:block;color:inherit;text-decoration:none}.cti-cms-card{transition:transform .18s ease,border-color .18s ease}.cti-cms-card:hover{transform:translateY(-3px);border-color:#31545a}.cti-cms-meta{font:600 11px monospace;letter-spacing:.14em;color:#21e6e6}.cti-cms-title{font-size:24px;line-height:1.15;margin:14px 0 10px}.cti-cms-dek,.cti-cms-empty,.cti-cms-detail-dek,.cti-cms-body{color:#9aa3b2;line-height:1.7}.cti-cms-read{display:inline-block;margin-top:18px;color:#21e6e6}.cti-cms-detail{max-width:920px}.cti-cms-back{display:inline-block;margin-bottom:30px;color:#21e6e6}.cti-cms-detail-title{font-size:clamp(38px,6vw,68px);line-height:1.04;letter-spacing:-.035em}.cti-cms-detail-dek{font-size:20px}.cti-cms-hero{width:100%;border-radius:14px;margin:28px 0}.cti-cms-body{font-size:18px}.cti-cms-body p{margin:0 0 1.3em}@media(max-width:720px){.cti-cms-root{padding:32px 20px}}@media(prefers-reduced-motion:reduce){.cti-cms-card{transition:none}.cti-cms-card:hover{transform:none}}';var s=document.createElement('style');s.textContent=css;document.head.appendChild(s);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();window.addEventListener('hashchange',load);
})();