(function(){
'use strict';
var route=(location.hash||'').replace(/^#\/?/,'').split('?')[0];
var typeMap={blog:'blog',research:'research','case-studies':'case-study'};
function track(n,d){if(window.CTI_RC11&&window.CTI_RC11.track)window.CTI_RC11.track(n,d||{});}
function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;}
function findEmpty(){return Array.from(document.querySelectorAll('main,section,div')).find(function(n){return /Content API is unavailable\.|Vendor API unavailable\.|No published items yet\./.test(n.textContent||'');});}
function card(item){var a=el('article','cti-cms-card');a.append(el('div','cti-cms-meta',(item.category||item.type||'Intelligence').toUpperCase()+(item.publishedAt?' · '+new Date(item.publishedAt).toLocaleDateString():'')),el('h2','cti-cms-title',item.title),el('p','cti-cms-dek',item.dek||''));return a;}
function renderContent(data){var root=findEmpty();if(!root)return;root.innerHTML='';root.classList.add('cti-cms-root');var bar=el('div','cti-cms-toolbar');bar.append(el('span','cti-live-dot','PUBLISHED'),el('span','',data.count+' items'));root.append(bar);var grid=el('div','cti-cms-grid');data.items.forEach(function(i){grid.append(card(i))});if(!data.items.length)grid.append(el('div','cti-cms-empty','Publishing system connected. No published items in this channel yet.'));root.append(grid);track('cms_content_loaded',{route:route,count:data.count});}
function renderVendors(data){var root=findEmpty();if(!root)return;root.innerHTML='';root.classList.add('cti-cms-root');var grid=el('div','cti-cms-grid');data.vendors.forEach(function(v){var c=el('article','cti-cms-card');c.append(el('div','cti-cms-meta',(v.category||'Vendor')+(v.priority?' · PRIORITY':'')),el('h2','cti-cms-title',v.name),el('p','cti-cms-dek',v.summary||''));grid.append(c)});if(!data.vendors.length)grid.append(el('div','cti-cms-empty','Vendor intelligence publishing is connected. Catalog records will appear after approval.'));root.append(grid);track('vendor_api_loaded',{count:(data.stats&&data.stats.tracked)||data.vendors.length});}
function load(){var cfg=window.CTI_CONVERSION||{};var url=route==='vendors'?(cfg.vendorsPath||'/api/vendors.php'):(cfg.contentPath||'/api/content.php')+'?type='+encodeURIComponent(typeMap[route]||'');if(route!=='vendors'&&!typeMap[route])return;fetch(url,{credentials:'same-origin',cache:'no-store'}).then(function(r){if(!r.ok)throw Error('http_'+r.status);return r.json()}).then(function(d){route==='vendors'?renderVendors(d):renderContent(d)}).catch(function(e){var root=findEmpty();if(root){root.innerHTML='';root.classList.add('cti-cms-root');root.append(el('div','cti-cms-empty','Publishing service is temporarily unavailable. Core site navigation and buyer workflows remain available.'));}track('dynamic_cms_unavailable',{route:route,error:String(e.message||e)});});}
var css='.cti-cms-root{max-width:1200px;margin:0 auto;padding:48px 28px 80px}.cti-cms-toolbar{display:flex;gap:12px;align-items:center;margin-bottom:24px;color:#9aa3b2}.cti-live-dot{color:#21e6e6;font:600 11px monospace;letter-spacing:.14em}.cti-cms-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}.cti-cms-card,.cti-cms-empty{border:1px solid #252b34;background:#101216;border-radius:14px;padding:28px}.cti-cms-meta{font:600 11px monospace;letter-spacing:.14em;color:#21e6e6}.cti-cms-title{font-size:24px;line-height:1.15;margin:14px 0 10px}.cti-cms-dek,.cti-cms-empty{color:#9aa3b2;line-height:1.6}@media(max-width:720px){.cti-cms-root{padding:32px 20px}}';var s=document.createElement('style');s.textContent=css;document.head.appendChild(s);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();window.addEventListener('hashchange',function(){route=(location.hash||'').replace(/^#\/?/,'').split('?')[0];load()});
})();