<?php
declare(strict_types=1);
const CTI_API_VERSION='2026-08-13';const CTI_MAX_BODY_BYTES=65536;
function cti_json(int $s,array $p):never{http_response_code($s);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');echo json_encode($p,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function cti_require_post():void{if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST'){header('Allow: POST');cti_json(405,['ok'=>false,'error'=>'method_not_allowed']);}}
function cti_read_json():array{$n=(int)($_SERVER['CONTENT_LENGTH']??0);if($n>CTI_MAX_BODY_BYTES)cti_json(413,['ok'=>false,'error'=>'payload_too_large']);if(!str_starts_with(strtolower((string)($_SERVER['CONTENT_TYPE']??'')),'application/json'))cti_json(415,['ok'=>false,'error'=>'content_type_must_be_application_json']);$raw=file_get_contents('php://input');try{$d=json_decode((string)$raw,true,64,JSON_THROW_ON_ERROR);}catch(Throwable){cti_json(400,['ok'=>false,'error'=>'invalid_json']);}if(!is_array($d))cti_json(400,['ok'=>false,'error'=>'json_object_required']);return$d;}
function cti_runtime_dir():string{$d=trim((string)getenv('CTI_RUNTIME_DIR'))?:dirname(__DIR__).'/.cti_runtime';if(!is_dir($d)&&!mkdir($d,0700,true)&&!is_dir($d))cti_json(503,['ok'=>false,'error'=>'runtime_storage_unavailable']);return$d;}
function cti_hash_ip():string{return hash_hmac('sha256',(string)($_SERVER['REMOTE_ADDR']??'unknown'),(string)(getenv('CTI_IP_HASH_SALT')?:'cti-staging'));}
function cti_rate_limit(string $b,int $l=30,int $w=60):void{$d=cti_runtime_dir().'/rate';@mkdir($d,0700,true);$p=$d.'/'.hash('sha256',$b.':'.cti_hash_ip()).'.json';$now=time();$x=is_file($p)?json_decode((string)file_get_contents($p),true):null;$s=is_array($x)?$x:['start'=>$now,'count'=>0];if($now-(int)$s['start']>=$w)$s=['start'=>$now,'count'=>0];$s['count']++;file_put_contents($p,json_encode($s),LOCK_EX);if($s['count']>$l)cti_json(429,['ok'=>false,'error'=>'rate_limited']);}
function cti_clean_scalar(mixed $v,int $max=500):?string{if($v===null||!is_scalar($v))return null;$s=trim((string)$v);return$s===''?null:mb_substr($s,0,$max);}
function cti_bool(mixed $v):bool{return$v===true||$v===1||$v==='1'||$v==='true';}
function cti_audit(string $stream,array $r):void{$d=cti_runtime_dir().'/audit';@mkdir($d,0700,true);$r+=['serverTs'=>gmdate('c'),'ipHash'=>cti_hash_ip()];file_put_contents($d.'/'.preg_replace('/[^a-z0-9_-]/i','_',$stream).'.jsonl',json_encode($r,JSON_UNESCAPED_SLASHES)."\n",FILE_APPEND|LOCK_EX);}
function cti_auth(array $allowed=['editor','admin']):array{$auth=trim((string)($_SERVER['HTTP_AUTHORIZATION']??''));$tokens=['admin'=>trim((string)getenv('CTI_CMS_ADMIN_TOKEN')),'editor'=>trim((string)getenv('CTI_CMS_EDITOR_TOKEN'))];foreach($tokens as $role=>$token){if($token!==''&&hash_equals('Bearer '.$token,$auth)&&in_array($role,$allowed,true))return['role'=>$role];}cti_json(401,['ok'=>false,'error'=>'cms_auth_required']);}
function cti_atomic_store(string $name,array $data):void{$d=cti_runtime_dir().'/cms';@mkdir($d,0700,true);$p=$d.'/'.$name;$history=$d.'/history';@mkdir($history,0700,true);if(is_file($p))@copy($p,$history.'/'.$name.'.'.gmdate('Ymd_His').'.bak');$tmp=$p.'.tmp.'.bin2hex(random_bytes(4));file_put_contents($tmp,json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);rename($tmp,$p);}
function cti_store_load(string $name,array $default):array{$d=cti_runtime_dir().'/cms';@mkdir($d,0700,true);$p=$d.'/'.$name;if(!is_file($p))cti_atomic_store($name,$default);$x=json_decode((string)file_get_contents($p),true);return is_array($x)?$x:$default;}
function cti_request_id():string{$v=trim((string)($_SERVER['HTTP_IDEMPOTENCY_KEY']??''));return($v!==''&&preg_match('/^[A-Za-z0-9:_\-.]{8,160}$/',$v))?$v:'cti:'.bin2hex(random_bytes(16));}
function cti_idempotency_read(string $id):?array{$p=cti_runtime_dir().'/idempotency/'.hash('sha256',$id).'.json';if(!is_file($p))return null;$x=json_decode((string)file_get_contents($p),true);return is_array($x)?$x:null;}
function cti_idempotency_write(string $id,array $r):void{$d=cti_runtime_dir().'/idempotency';@mkdir($d,0700,true);file_put_contents($d.'/'.hash('sha256',$id).'.json',json_encode($r),LOCK_EX);}
function cti_http_form(string $url,array $fields):array{if(!function_exists('curl_init'))throw new RuntimeException('curl_unavailable');$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>12,CURLOPT_HTTPHEADER=>['Accept: application/json','Content-Type: application/x-www-form-urlencoded'],CURLOPT_POSTFIELDS=>http_build_query($fields)]);$body=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$error=curl_error($ch);curl_close($ch);if($body===false||$error!=='')throw new RuntimeException('upstream_transport_error');$decoded=json_decode((string)$body,true);return['status'=>$status,'body'=>is_array($decoded)?$decoded:['raw'=>(string)$body]];}
function cti_suitecrm_call(string $endpoint,string $method,array $params):array{return cti_http_form($endpoint,['method'=>$method,'input_type'=>'JSON','response_type'=>'JSON','rest_data'=>json_encode($params,JSON_UNESCAPED_SLASHES)]);}
function cti_suitecrm_create_lead(array $lead):array{$base=rtrim(trim((string)getenv('CTI_CRM_URL')),'/');$user=trim((string)getenv('CTI_CRM_USER'));$password=(string)getenv('CTI_CRM_PASSWORD');if($base===''||$user===''||$password==='')return['ok'=>false,'error'=>'crm_not_configured'];if(!str_starts_with(strtolower($base),'https://'))return['ok'=>false,'error'=>'crm_https_required'];$ep=$base.'/service/v4_1/rest.php';$login=cti_suitecrm_call($ep,'login',['user_auth'=>['user_name'=>$user,'password'=>preg_match('/^[a-f0-9]{32}$/i',$password)?strtolower($password):md5($password),'version'=>'1'],'application_name'=>'CTI Website','name_value_list'=>[]]);$session=$login['body']['id']??null;if(!$session)return['ok'=>false,'error'=>'crm_login_failed'];$name=trim((string)($lead['identity']['name']??'Website Lead'));$parts=preg_split('/\s+/',$name,2);$values=[['name'=>'first_name','value'=>$parts[0]??'Website'],['name'=>'last_name','value'=>$parts[1]??'Lead'],['name'=>'email1','value'=>$lead['identity']['email']],['name'=>'account_name','value'=>$lead['identity']['company']],['name'=>'title','value'=>$lead['identity']['role']],['name'=>'lead_source','value'=>'Web Site'],['name'=>'status','value'=>'New'],['name'=>'description','value'=>json_encode(['ctiRequestId'=>$lead['requestId'],'qualificationState'=>$lead['qualificationState'],'intent'=>$lead['intent'],'attribution'=>$lead['attribution'],'permission'=>$lead['permission']],JSON_UNESCAPED_SLASHES)]];$created=cti_suitecrm_call($ep,'set_entry',['session'=>$session,'module_name'=>'Leads','name_value_list'=>$values]);$id=$created['body']['id']??null;return$id?['ok'=>true,'crmRecordId'=>(string)$id,'crmModule'=>'Leads']:['ok'=>false,'error'=>'crm_create_failed'];}
