<?php
declare(strict_types=1);

const CTI_API_VERSION = '2026-08-13';
const CTI_MAX_BODY_BYTES = 32768;
function cti_json(int $status,array $payload):never{http_response_code($status);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');echo json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function cti_request_id():string{$v=trim((string)($_SERVER['HTTP_IDEMPOTENCY_KEY']??''));return($v!==''&&preg_match('/^[A-Za-z0-9:_\-.]{8,160}$/',$v))?$v:'cti:'.bin2hex(random_bytes(16));}
function cti_require_post():void{if(($_SERVER['REQUEST_METHOD']??'')!=='POST'){header('Allow: POST');cti_json(405,['ok'=>false,'error'=>'method_not_allowed','apiVersion'=>CTI_API_VERSION]);}}
function cti_read_json():array{$n=(int)($_SERVER['CONTENT_LENGTH']??0);if($n>CTI_MAX_BODY_BYTES)cti_json(413,['ok'=>false,'error'=>'payload_too_large']);$ct=strtolower((string)($_SERVER['CONTENT_TYPE']??''));if(!str_starts_with($ct,'application/json'))cti_json(415,['ok'=>false,'error'=>'content_type_must_be_application_json']);$raw=file_get_contents('php://input');if($raw===false||strlen($raw)>CTI_MAX_BODY_BYTES)cti_json(413,['ok'=>false,'error'=>'payload_too_large']);try{$d=json_decode($raw,true,64,JSON_THROW_ON_ERROR);}catch(Throwable $e){cti_json(400,['ok'=>false,'error'=>'invalid_json']);}if(!is_array($d))cti_json(400,['ok'=>false,'error'=>'json_object_required']);return $d;}
function cti_runtime_dir():string{$c=trim((string)getenv('CTI_RUNTIME_DIR'));$d=$c!==''?$c:dirname(__DIR__).'/.cti_runtime';if(!is_dir($d)&&!mkdir($d,0700,true)&&!is_dir($d))cti_json(503,['ok'=>false,'error'=>'runtime_storage_unavailable']);return $d;}
function cti_hash_ip():string{$ip=(string)($_SERVER['REMOTE_ADDR']??'unknown');$salt=(string)(getenv('CTI_IP_HASH_SALT')?:'cti-staging');return hash_hmac('sha256',$ip,$salt);}
function cti_rate_limit(string $bucket,int $limit=20,int $window=60):void{$dir=cti_runtime_dir().'/rate';if(!is_dir($dir))@mkdir($dir,0700,true);$path=$dir.'/'.hash('sha256',$bucket.':'.cti_hash_ip()).'.json';$now=time();$state=['start'=>$now,'count'=>0];$fh=fopen($path,'c+');if(!$fh)cti_json(503,['ok'=>false,'error'=>'rate_limit_storage_unavailable']);flock($fh,LOCK_EX);$raw=stream_get_contents($fh);if($raw){$x=json_decode($raw,true);if(is_array($x))$state=$x;}if(($now-(int)$state['start'])>=$window)$state=['start'=>$now,'count'=>0];$state['count']=(int)$state['count']+1;ftruncate($fh,0);rewind($fh);fwrite($fh,json_encode($state));fflush($fh);flock($fh,LOCK_UN);fclose($fh);if($state['count']>$limit){header('Retry-After: '.max(1,$window-($now-(int)$state['start'])));cti_json(429,['ok'=>false,'error'=>'rate_limited']);}}
function cti_clean_scalar(mixed $v,int $max=500):?string{if($v===null||!is_scalar($v))return null;$s=trim((string)$v);return $s===''?null:mb_substr($s,0,$max);}
function cti_bool(mixed $v):bool{return $v===true||$v===1||$v==='1'||$v==='true';}
function cti_audit(string $stream,array $r):void{$d=cti_runtime_dir().'/audit';if(!is_dir($d))@mkdir($d,0700,true);$r['serverTs']=gmdate('c');$r['ipHash']=cti_hash_ip();@file_put_contents($d.'/'.preg_replace('/[^a-z0-9_-]/i','_',$stream).'.jsonl',json_encode($r,JSON_UNESCAPED_SLASHES)."\n",FILE_APPEND|LOCK_EX);}
function cti_idempotency_read(string $id):?array{$d=cti_runtime_dir().'/idempotency';if(!is_dir($d))@mkdir($d,0700,true);$p=$d.'/'.hash('sha256',$id).'.json';if(!is_file($p))return null;$x=json_decode((string)file_get_contents($p),true);return is_array($x)?$x:null;}
function cti_idempotency_write(string $id,array $r):void{$d=cti_runtime_dir().'/idempotency';if(!is_dir($d))@mkdir($d,0700,true);file_put_contents($d.'/'.hash('sha256',$id).'.json',json_encode($r,JSON_UNESCAPED_SLASHES),LOCK_EX);}
function cti_http_form(string $url,array $fields):array{if(!function_exists('curl_init'))throw new RuntimeException('curl_unavailable');$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>12,CURLOPT_HTTPHEADER=>['Accept: application/json','Content-Type: application/x-www-form-urlencoded'],CURLOPT_POSTFIELDS=>http_build_query($fields)]);$body=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$error=curl_error($ch);curl_close($ch);if($body===false||$error!=='')throw new RuntimeException('upstream_transport_error');$decoded=json_decode((string)$body,true);return['status'=>$status,'body'=>is_array($decoded)?$decoded:['raw'=>(string)$body]];}
function cti_suitecrm_call(string $endpoint,string $method,array $params):array{return cti_http_form($endpoint,['method'=>$method,'input_type'=>'JSON','response_type'=>'JSON','rest_data'=>json_encode($params,JSON_UNESCAPED_SLASHES)]);}
function cti_suitecrm_create_lead(array $lead):array{$base=rtrim(trim((string)getenv('CTI_CRM_URL')),'/');$user=trim((string)getenv('CTI_CRM_USER'));$password=(string)getenv('CTI_CRM_PASSWORD');if($base===''||$user===''||$password==='')return['ok'=>false,'error'=>'crm_not_configured'];if(!str_starts_with(strtolower($base),'https://'))return['ok'=>false,'error'=>'crm_https_required'];$endpoint=$base.'/service/v4_1/rest.php';$passwordHash=preg_match('/^[a-f0-9]{32}$/i',$password)?strtolower($password):md5($password);$login=cti_suitecrm_call($endpoint,'login',['user_auth'=>['user_name'=>$user,'password'=>$passwordHash,'version'=>'1'],'application_name'=>'CTI Website','name_value_list'=>[]]);$session=$login['body']['id']??null;if($login['status']>=400||!$session)return['ok'=>false,'error'=>'crm_login_failed','status'=>$login['status']];$name=trim((string)($lead['identity']['name']??'Website Lead'));$parts=preg_split('/\s+/',$name,2);$values=[['name'=>'first_name','value'=>$parts[0]??'Website'],['name'=>'last_name','value'=>$parts[1]??'Lead'],['name'=>'email1','value'=>$lead['identity']['email']],['name'=>'account_name','value'=>$lead['identity']['company']],['name'=>'title','value'=>$lead['identity']['role']],['name'=>'lead_source','value'=>'Web Site'],['name'=>'status','value'=>'New'],['name'=>'description','value'=>json_encode(['ctiRequestId'=>$lead['requestId'],'qualificationState'=>$lead['qualificationState'],'intent'=>$lead['intent'],'attribution'=>$lead['attribution'],'permission'=>$lead['permission']],JSON_UNESCAPED_SLASHES)]];$created=cti_suitecrm_call($endpoint,'set_entry',['session'=>$session,'module_name'=>'Leads','name_value_list'=>$values]);$id=$created['body']['id']??null;if($created['status']>=400||!$id)return['ok'=>false,'error'=>'crm_create_failed','status'=>$created['status']];return['ok'=>true,'crmRecordId'=>(string)$id,'crmModule'=>'Leads'];}
