<?php
declare(strict_types=1);require __DIR__.'/_lib.php';
const TYPES=['blog','research','resource','case-study'];
function loadc():array{return cti_store_load('content.json',['schema'=>'cti.cms.v3','updatedAt'=>gmdate('c'),'items'=>[]]);}
function norm(array $x,?array $old=null):array{$type=cti_clean_scalar($x['type']??$old['type']??null,40);$title=cti_clean_scalar($x['title']??$old['title']??null,180);$slug=cti_clean_scalar($x['slug']??$old['slug']??null,180);if(!$type||!in_array($type,TYPES,true)||!$title||!$slug||!preg_match('/^[a-z0-9-]+$/',$slug))cti_json(422,['ok'=>false,'error'=>'invalid_content']);$status=cti_clean_scalar($x['status']??$old['status']??'draft',20);if(!in_array($status,['draft','published','unpublished','archived'],true))cti_json(422,['ok'=>false,'error'=>'invalid_status']);return['id'=>$old['id']??cti_clean_scalar($x['id']??null,100)??'content:'.bin2hex(random_bytes(8)),'type'=>$type,'slug'=>$slug,'title'=>$title,'dek'=>cti_clean_scalar($x['dek']??$old['dek']??null,700),'body'=>cti_clean_scalar($x['body']??$old['body']??null,50000),'status'=>$status,'publishedAt'=>$status==='published'?($old['publishedAt']??gmdate('c')):null,'updatedAt'=>gmdate('c'),'author'=>cti_clean_scalar($x['author']??$old['author']??null,120),'category'=>cti_clean_scalar($x['category']??$old['category']??null,120),'topics'=>array_values(array_filter($x['topics']??$old['topics']??[], 'is_string')),'heroImage'=>cti_clean_scalar($x['heroImage']??$old['heroImage']??null,500),'seo'=>is_array($x['seo']??null)?$x['seo']:($old['seo']??[])];}
$m=$_SERVER['REQUEST_METHOD']??'GET';$s=loadc();
if($m==='GET'){$admin=($_GET['admin']??'')==='1';if($admin)cti_auth();$type=cti_clean_scalar($_GET['type']??null,40);$slug=cti_clean_scalar($_GET['slug']??null,180);$items=array_values(array_filter($s['items'],fn($i)=>($admin||($i['status']??'')==='published')&&(!$type||($i['type']??'')===$type)&&(!$slug||($i['slug']??'')===$slug)));cti_json(200,['ok'=>true,'schema'=>'cti.cms.v3','count'=>count($items),'items'=>$items]);}
cti_auth();cti_rate_limit('cms-write',60,60);$in=cti_read_json();$id=cti_clean_scalar($in['id']??null,100);$idx=null;foreach($s['items'] as $k=>$v)if(($id&&($v['id']??'')===$id)||((isset($in['type'],$in['slug']))&&($v['type']??'')===$in['type']&&($v['slug']??'')===$in['slug'])){$idx=$k;break;}
if($m==='DELETE'){cti_auth(['admin']);if($idx===null)cti_json(404,['ok'=>false,'error'=>'not_found']);$s['items'][$idx]['status']='archived';$s['items'][$idx]['updatedAt']=gmdate('c');cti_atomic_store('content.json',$s);cti_audit('cms',['action'=>'archive','id'=>$s['items'][$idx]['id']]);cti_json(200,['ok'=>true,'item'=>$s['items'][$idx]]);}
if(!in_array($m,['POST','PUT','PATCH'],true))cti_json(405,['ok'=>false,'error'=>'method_not_allowed']);$old=$idx!==null?$s['items'][$idx]:null;$item=norm($in,$old);if($idx===null)$s['items'][]=$item;else$s['items'][$idx]=$item;$s['updatedAt']=gmdate('c');cti_atomic_store('content.json',$s);cti_audit('cms',['action'=>$old?'update':'create','id'=>$item['id'],'status'=>$item['status']]);cti_json($old?200:201,['ok'=>true,'item'=>$item]);