<?php
declare(strict_types=1);
require __DIR__ . '/_lib.php';

function cti_vendor_store(): string {
    $dir=cti_runtime_dir().'/cms'; if(!is_dir($dir)&&!mkdir($dir,0700,true)&&!is_dir($dir))cti_json(503,['ok'=>false,'error'=>'cms_storage_unavailable']);
    $path=$dir.'/vendors.json'; if(!is_file($path))file_put_contents($path,json_encode(['schema'=>'cti.vendors.v2','updatedAt'=>gmdate('c'),'vendors'=>[]],JSON_PRETTY_PRINT),LOCK_EX); return $path;
}
function cti_vendor_load(): array{$d=json_decode((string)file_get_contents(cti_vendor_store()),true);return is_array($d)?$d:['schema'=>'cti.vendors.v2','updatedAt'=>gmdate('c'),'vendors'=>[]];}
function cti_vendor_auth(): void{$e=trim((string)getenv('CTI_CMS_ADMIN_TOKEN'));$a=trim((string)($_SERVER['HTTP_AUTHORIZATION']??''));if($e===''||!hash_equals('Bearer '.$e,$a))cti_json(401,['ok'=>false,'error'=>'cms_auth_required']);}
function cti_vendor_list(mixed $v,int $max=160):array{if(!is_array($v))return[];return array_values(array_filter(array_map(fn($x)=>cti_clean_scalar($x,$max),$v)));}
function cti_vendor_normalize(array $v):array{
 $name=cti_clean_scalar($v['name']??null,180);$slug=cti_clean_scalar($v['slug']??null,180);if(!$name||!$slug||!preg_match('/^[a-z0-9-]+$/',$slug))cti_json(422,['ok'=>false,'error'=>'name_and_slug_required']);
 $status=cti_clean_scalar($v['status']??'draft',20);if(!in_array($status,['draft','published','archived'],true))cti_json(422,['ok'=>false,'error'=>'invalid_status']);
 return ['id'=>cti_clean_scalar($v['id']??null,100)?:'vendor:'.bin2hex(random_bytes(8)),'name'=>$name,'slug'=>$slug,'category'=>cti_clean_scalar($v['category']??null,120),'segment'=>cti_clean_scalar($v['segment']??null,120),'website'=>cti_clean_scalar($v['website']??null,500),'summary'=>cti_clean_scalar($v['summary']??null,2000),'body'=>cti_clean_scalar($v['body']??null,30000),'priority'=>cti_bool($v['priority']??false),'buyingTriggers'=>cti_vendor_list($v['buyingTriggers']??[],120),'activationPlays'=>cti_vendor_list($v['activationPlays']??[],160),'evidenceIds'=>cti_vendor_list($v['evidenceIds']??[],100),'status'=>$status,'publishedAt'=>$status==='published'?(cti_clean_scalar($v['publishedAt']??null,40)?:gmdate('c')):cti_clean_scalar($v['publishedAt']??null,40),'updatedAt'=>gmdate('c')];
}
$method=$_SERVER['REQUEST_METHOD']??'GET';
if($method==='GET'){$admin=($_GET['admin']??'')==='1';if($admin)cti_vendor_auth();$s=cti_vendor_load();$q=strtolower(trim((string)($_GET['q']??'')));$category=trim((string)($_GET['category']??''));$status=trim((string)($_GET['status']??''));$vendors=array_values(array_filter($s['vendors']??[],function($v)use($admin,$q,$category,$status){if(!$admin&&($v['status']??'')!=='published')return false;if($admin&&$status&&($v['status']??'')!==$status)return false;if($category!==''&&($v['category']??'')!==$category)return false;if($q!==''&&!str_contains(strtolower((string)json_encode($v)),$q))return false;return true;}));$categories=array_values(array_unique(array_filter(array_map(fn($v)=>$v['category']??null,$vendors))));$priority=count(array_filter($vendors,fn($v)=>!empty($v['priority'])));cti_json(200,['ok'=>true,'schema'=>'cti.vendors.v2','updatedAt'=>$s['updatedAt']??null,'stats'=>['tracked'=>count($vendors),'categories'=>count($categories),'priority'=>$priority],'categories'=>$categories,'vendors'=>$vendors]);}
if(!in_array($method,['POST','PUT'],true)){header('Allow: GET, POST, PUT');cti_json(405,['ok'=>false,'error'=>'method_not_allowed']);}
cti_vendor_auth();cti_rate_limit('vendor-write',60,60);$input=cti_read_json();$vendor=cti_vendor_normalize($input);$s=cti_vendor_load();$vendors=$s['vendors']??[];$replaced=false;foreach($vendors as $i=>$existing)if(($existing['id']??'')===$vendor['id']||($existing['slug']??'')===$vendor['slug']){$vendor['id']=$existing['id']??$vendor['id'];$vendors[$i]=$vendor;$replaced=true;break;}if(!$replaced)$vendors[]=$vendor;$s=['schema'=>'cti.vendors.v2','updatedAt'=>gmdate('c'),'vendors'=>$vendors];file_put_contents(cti_vendor_store(),json_encode($s,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);cti_audit('vendors',['action'=>$replaced?'update':'create','vendorId'=>$vendor['id'],'slug'=>$vendor['slug'],'status'=>$vendor['status']]);cti_json($replaced?200:201,['ok'=>true,'vendor'=>$vendor]);
